

# Connectivity Status Results   {-}
In the Berland and Wildhay watersheds, X km of cold-water salmonids habitat are currently connected to the ocean and X km are disconnected from it. This means that X% of the X km of total habitat is connected. 

## Structure Count  {-}

In the Berland and Wildhay watersheds, X structures potentially disconnect cold-water salmonids habitat.  


## Map  {-}

![Figure 1: Map of cold-water salmonids habitat and structures that are confirmed or potential barriers to fish passage in the Berland and Wildhay watersheds as of July 2026. Structure data were obtained from ABFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more cold-water salmonid species could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more cold-water salmonids for spawning and/or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures).](images/HacMap.png)


## Habitat Accumulation Curve {-}

![Figure 2: Habitat Accumulation Curve (HAC) showing structures in the Berland and Wildhay watersheds as of July 2026. Structures are ranked based on how much (km) habitat for cold-water salmonids is upstream. The y-axis represents the cumulative amount of potential habitat gain (km). Habitat upstream of unassessed structures is considered disconnected until field assessments are completed.](images/BW_HAC.png)

## Habitat Accumulation Summary Table  {-}

Table 1: Labelled structures in the Habitat Accumulation Curve (Figure 2), their rank, and upstream habitat for cold-water salmonids in Berland and Wildhay watersheds. Habitat gain represents the amount (km) of habitat upstream of that structure to the next structure and depicts the potential gain in habitat if passage at that structure was restored.  


## Goals {-}

The planning group was reminded to develop goals that are SMART (specific, measurable, achievable, results-oriented and time-bound. To move beyond the status quo of 86.4% connectivity, after some discussion, the group agreed to the following proposed Goals: 

 - By 2027, the proportion of linear habitat accessible to Coldwater Salmonids in the Berland-Wildhay Watershed will increase from 86.4% to 90%.  

 - By 2032, the proportion of linear habitat accessible to Coldwater Salmonids in the Berland-Wildhay Watershed will increase from 86.4% to 95%. 

