# Progress Reporting  {-}

## Progress Summary {-}

This WCRP was initiated in 2022. Five planning meetings were held with the project management team from February 2022- May 2023, to discuss spatial and species scope. In 2025, Poseiden Environmental Ltd was contracted to complete 34 barrier assessments (Shewan, 2025a, 2025b). 

## Rehabilitated Barriers  {-}

No barriers have been rehabilitated through the implementation of this WCRP as of July 2026. 


## Annual Progress Report {-}
Since 2022, the following actions were completed: 

 - Barrier assessments were completed for 29 structures, resulting in 6 structures confirmed as barriers and 23 structures excluded as passable or non-existent, or because there was no habitat upstream. Five additional structures were visited but could not be accessed.  

 - In-depth habitat or passage assessments were completed at 2 barriers, resulting in 2 being identified as priorities. 

 - The connectivity model was updated based on the above actions, and outputs were incorporated into this WCRP. 